// ============================================
// FOOD THOUGHTS — a bank of short, original food/kitchen/gratitude thoughts
// printed on custom bills ("Thought for the day"). Plain ASCII on purpose so
// every thermal printer prints it correctly. One thought per calendar day,
// chosen deterministically from the date, so every bill printed on the same
// day carries the same thought and the sequence does not repeat for years.
// ============================================
export const FOOD_THOUGHTS = [
 "A fresh tomato is sunshine you can slice.",
 "Good food begins in good soil.",
 "Every farmer's hand is in your plate.",
 "Fresh vegetables are the quiet heroes of every kitchen.",
 "A kitchen that smells of onions is a kitchen with a story.",
 "Eat colours, and your plate will paint you healthy.",
 "The best recipe is fresh ingredients and a patient heart.",
 "Cooking is love you can taste.",
 "A full basket today is a happy table tonight.",
 "Fresh from the market, fresh on your table.",
 "Simple food, cooked with care, beats any feast.",
 "Let your vegetables be fresh and your worries be few.",
 "Every meal is a small chance to look after yourself.",
 "Good morning starts with good produce.",
 "Wash the vegetables, warm the kitchen, welcome the day.",
 "A ripe fruit teaches you to wait and enjoy.",
 "Where there is fresh food, there is a reason to gather.",
 "A home-cooked meal says what words cannot.",
 "Choose fresh, cook slow, share more.",
 "Gratitude tastes best with warm rice and sambar.",
 "The market wakes before the city so your kitchen can too.",
 "Fresh greens, fresh mind.",
 "One carrot a day keeps the dull meals away.",
 "Small portions of kindness make any meal bigger.",
 "Behind every bite are many hands that worked for you.",
 "Fresh food is the oldest form of happiness.",
 "Cook what the season gives you.",
 "Nothing beats vegetables picked at dawn.",
 "A meal shared is a meal doubled.",
 "Healthy living starts at the vegetable basket.",
 "Let every plate be a little festival.",
 "Peel an onion, find a lesson in patience.",
 "The kitchen is the heart where the family meets.",
 "Freshness is the best seasoning.",
 "Ripe mangoes make even a Monday sweet.",
 "A spoon of ghee and a heart of gold.",
 "Eat well today so tomorrow smiles back.",
 "Good cooks listen to their ingredients.",
 "Fresh coriander can turn a plain dish into a celebration.",
 "Every sunrise deserves a good breakfast.",
 "Great meals come from honest ingredients.",
 "A basket of fruit is a basket of joy.",
 "The simplest dal can feel like a hug.",
 "Cooking slowly is another way of caring.",
 "Fruit first, worries later.",
 "Let food be a reason to pause and breathe.",
 "A good potato knows how to be everything.",
 "Taste the season, trust the farmer.",
 "Plates look prettier with greens on them.",
 "A little turmeric, a lot of tradition.",
 "Home food heals what hurry hurts.",
 "Chopping vegetables is the music of a kitchen.",
 "Where vegetables are fresh, dinners are happy.",
 "Fresh ginger warms the day and the heart.",
 "Take a bite, take your time.",
 "A banana a day brightens the way.",
 "Be like a good vegetable: simple, useful and fresh.",
 "Food made with love needs no recipe.",
 "Eat together, stay together.",
 "A fresh lemon can brighten any moment.",
 "Plant a seed, grow patience.",
 "The best view is a table full of fresh food.",
 "Fill your basket with colour and your day with calm.",
 "Cook it fresh, eat it warm, share it kindly.",
 "A pinch of salt, a handful of gratitude.",
 "Fresh beans, fresh start.",
 "Every dish has a farmer behind it.",
 "Let the aroma of tamarind rasam welcome the evening.",
 "Healthy habits start in the kitchen.",
 "Good vegetables need little; good company needs less.",
 "Spinach for strength, smiles for free.",
 "Where the heart is, there is always a pot simmering.",
 "A meal made with care is a gift to yourself.",
 "Fresh fruit is nature's candy.",
 "Honest food builds honest health.",
 "Smell the curry leaves and remember home.",
 "A good brinjal curry is worth the wait.",
 "Joy is a plate of hot idlis on a rainy morning.",
 "A day well begun is a day half won, and breakfast helps.",
 "When in doubt, add more vegetables.",
 "Appreciate the pumpkin: slow, sweet and steady.",
 "Mealtime is the smallest holiday of the day.",
 "A garden on your plate is the best medicine.",
 "Freshness cannot be rushed, only respected.",
 "Savour the small things, starting with the next bite.",
 "The greenest leaf carries the brightest energy.",
 "Food tastes better when the table is full of laughter.",
 "Cook with joy and the dish will know.",
 "The market is an orchestra of fresh voices.",
 "Kind words and warm food travel the farthest.",
 "Good health is a basketful of fresh choices.",
 "Let your dinner be light and your heart lighter.",
 "Eat the rainbow, live the rainbow.",
 "A well-stocked kitchen is a calm mind.",
 "Every small onion hides a big flavour.",
 "Fresh cabbage crunch is nature's applause.",
 "The sweetest fruit is the one shared.",
 "Our best memories are cooked slowly.",
 "Hot rice, ghee and a little love: a perfect meal.",
 "The soil gives, the farmer cares, we are fed.",
 "Tomatoes do not hurry; they ripen in their own time.",
 "A basket from the market is a basket of blessings.",
 "A cup of tea tastes sweeter with a fresh snack.",
 "Be thankful for the food, the farmer and the day.",
 "Fresh produce, honest prices, happy kitchens.",
 "A well-cooked meal makes a long day shorter.",
 "Keep your spices fresh and your stories fresher.",
 "Vegetables are the colours of good health.",
 "A ripe papaya is a morning blessing.",
 "Let each plate carry a little peace.",
 "Peas in a pod, family at the table.",
 "Cooking for others is the quietest kind of love.",
 "Fresh curry leaves make every tadka sing.",
 "Choose the vegetable that looks you in the eye.",
 "Wisdom is knowing which tomato is ready today.",
 "Fresh is not a promise; it is a practice.",
 "The best ingredient in any kitchen is time shared.",
 "When the pot bubbles, worries drift away.",
 "Grace begins with a grateful first bite.",
 "Beans, brinjal and a bit of patience.",
 "The earth feeds those who respect it.",
 "Salt makes food taste better; kindness makes it feel better.",
 "Every ripe guava is a small surprise.",
 "Good greens, good grains, good days.",
 "Bring home freshness and the house smiles.",
 "A fresh coconut is a festival in a shell.",
 "Let the vegetable basket be the first thing you fill.",
 "Healthy food is never a punishment; it is a present.",
 "A pot of sambar can fix a long Monday.",
 "Nothing says welcome like a table that smells of home.",
 "Trust fresh produce to do the talking.",
 "Tonight's dinner is today's best decision.",
 "Vegetables grown with care taste of care.",
 "Gather around good food and let the day slow down.",
 "Garlic and ginger: the old friends of every kitchen.",
 "Enjoy the crunch of a fresh cucumber on a warm day.",
 "Wake up, wash up, eat fresh.",
 "A plate of papaya brightens any morning.",
 "The best seasoning is hunger and good company.",
 "Fresh peas shelled together make time fly.",
 "An empty basket is just a fresh beginning.",
 "Appreciate the onion; it makes us cry and cook.",
 "A sprinkle of coriander is a sprinkle of joy.",
 "Freshly cut fruit, freshly cleared mind.",
 "A little planning makes tomorrow's meal easy.",
 "The warmest welcome comes from a kitchen.",
 "Carrots remind us that good things grow quietly.",
 "Let your meals be simple and your gratitude big.",
 "Bite by bite, a healthier you.",
 "Food is memory you can eat.",
 "A fruit bowl on the table invites good habits.",
 "Where there is sambar, there is hope.",
 "Fresh drumstick in the pot, smile on the face.",
 "Every meal is a fresh chance to feel good.",
 "The finest dish is the one made with a calm mind.",
 "Cook like someone is coming to dinner, even when alone.",
 "A pinch of patience makes any gravy better.",
 "Let your ingredients be local and your joy global.",
 "Fresh beetroot, fresh blush.",
 "Choose food that comes from the earth, not from the wrapper.",
 "A day of good food is a day of good thoughts.",
 "A handful of fresh greens makes any dish feel alive.",
 "Slow food, warm hearts.",
 "Even the smallest chilli carries a big story.",
 "Mangoes remind us that summer is generous.",
 "Take care of your body; it cooks your dreams.",
 "An evening walk and a light dinner: the simplest wellness plan.",
 "Fresh from the farm, freshly loved at home.",
 "Mothers know the secret ingredient: attention.",
 "The way to a happy home is through a fresh kitchen.",
 "A basket of oranges is a basket of sunshine.",
 "Chop with care, cook with calm.",
 "A good vegetable market is a school of colours.",
 "Good food does not shout; it simply satisfies.",
 "The kitchen is where ordinary days become special.",
 "Every grain on your plate has a journey.",
 "Fresh produce is the easiest way to say, I care.",
 "Keep it fresh, keep it simple, keep it kind.",
 "Let the sweetness of fruit remind you to be gentle.",
 "Serve warm food and warm words.",
 "Hands that grow food deserve our thanks.",
 "A bowl of fresh fruit is a bowl of good intentions.",
 "Enjoy what you eat and where it came from.",
 "A fresh chilli teaches courage in small sizes.",
 "To cook is to create; to share is to complete.",
 "Let curd rice and a pickle end your day well.",
 "Radish, spinach, beans and cheer.",
 "The most delicious thing is fresh food shared on time.",
 "Keep your fridge full of colours.",
 "Today's lunch is tomorrow's energy.",
 "Always leave room for one more fruit.",
 "Chennai mornings smell of filter coffee and fresh idli.",
 "Koyambedu wakes at midnight so your morning can be fresh.",
 "Before the city rises, the market has already worked a day.",
 "Fresh from Koyambedu, straight to your kitchen.",
 "Tamil kitchens run on love, tamarind and patience.",
 "A drizzle of sesame oil and the whole house knows dinner is near.",
 "Pongal is gratitude served on a leaf.",
 "A banana leaf makes any meal feel like a feast.",
 "Sambar, rasam, curd: three chapters of one good story.",
 "Coconut chutney and hot dosa, the breakfast of champions.",
 "Filter coffee is a hug in a tumbler.",
 "Every Tamil home has a corner that smells of curry leaves.",
 "A summer afternoon calls for buttermilk and a long nap.",
 "Mango pickle is just summer saved in a jar.",
 "Rain outside, bajji inside: life is balanced.",
 "Fresh jasmine and fresh vegetables: two good smells.",
 "The kolam outside and the kootu inside welcome all.",
 "A leaf of curry leaf in the tadka is a sign of home.",
 "Temple prasadam tastes of faith and ghee.",
 "Murungai in the sambar, health in the family.",
 "Festivals are just good food with good company.",
 "Diwali sweets are shared, not counted.",
 "A plantain flower curry is patience turned delicious.",
 "Vazhaipoo, keerai, kootu: the old wisdom is still the best.",
 "Evenings are for tea, snacks and slow conversation.",
 "Rice is the quiet friend of every curry.",
 "A hot filter coffee turns any morning around.",
 "Grandmother's recipes are the best cookbooks never printed.",
 "The scent of tempering mustard is the sound of a kitchen waking up.",
 "A neatly stacked vegetable basket is a good week planned.",
 "Winter oranges, summer mangoes, monsoon corn: eat with the year.",
 "Tender coconut is nature's own cool drink.",
 "Fresh pomegranate: a thousand little rubies for your plate.",
 "Sweet lime on a hot day is a small miracle.",
 "Apples are best shared and sliced.",
 "Grapes taste better when shared by the handful.",
 "A ripe watermelon is summer's best story.",
 "Papaya, banana, guava: the humble heroes of every fruit plate.",
 "Pineapple teaches us that sweetness can wear armour.",
 "A bunch of bananas is a small family on the counter.",
 "Coconut water is the sound of a cool breeze.",
 "Jackfruit season is the season of patience and great reward.",
 "Strawberries remind us that small things are sweet.",
 "A fresh lime in the water makes any day lighter.",
 "Dates and a glass of milk: a quiet kind of rich.",
 "Dry fruits are small treasures for hungry days.",
 "Nuts and seeds: tiny packages of big energy.",
 "Sprouts for breakfast, spring in your step.",
 "Millets are the old grains with new relevance.",
 "Whole grains, whole days.",
 "Fresh dosa batter is the smell of tomorrow's breakfast.",
 "Yoghurt and a pinch of salt: the oldest cool-down.",
 "Honey on the tongue, thanks on the lips.",
 "A bowl of porridge is an old and gentle comfort.",
 "Moong dal, soft and simple, is a quiet blessing.",
 "Idli is a cloud you can eat.",
 "Fresh paneer is a small snow-white gift.",
 "Soft chapatis straight off the tawa are hard to beat.",
 "A basket of mixed vegetables is a weekly promise to yourself.",
 "Fresh leafy greens are the quickest route to a lighter plate.",
 "Ladies finger on a Sunday, laughter on a Monday.",
 "Bitter gourd teaches that not all good things are sweet.",
 "Snake gourd, ridge gourd, bottle gourd: the gentle family.",
 "Raw banana fry is a plain joy.",
 "Pumpkin kootu is a warm, sweet letter from the kitchen.",
 "Cluster beans, rice and rasam: a modest, perfect meal.",
 "Mushrooms remind us that good things grow in the shade.",
 "Fresh corn on a monsoon evening is hard to beat.",
 "A sweet potato roasted slowly is a lesson in patience.",
 "Peppers add colour to the plate and confidence to the cook.",
 "The red chilli is small, the fire is large.",
 "Mint is the freshest word in any recipe.",
 "A sprig of curry leaf is a signature of South India.",
 "Fenugreek leaves bring a bitter-sweet charm.",
 "Ginger tea in the rain is a small, warm victory.",
 "Pepper rasam clears the head and cheers the heart.",
 "Cardamom is a whisper of luxury in a cup of tea.",
 "Cloves and cinnamon bring whole festivals into the kitchen.",
 "Cumin crackling in oil is the opening note of good cooking.",
 "Jaggery is a sweet reminder of how our grandparents ate.",
 "Mustard seeds are small, but they announce the tadka loudly.",
 "A little hing makes a big difference.",
 "Fresh turmeric is sunshine from the earth.",
 "Black pepper is the quiet strength of the spice box.",
 "Salt in the right measure is wisdom.",
 "Good oil, fresh vegetables, honest spices: that is cooking.",
 "Your body is the only place you have to live; feed it well.",
 "A kind meal is the best medicine for a tired day.",
 "Fresh food does not need a label to prove itself.",
 "Try one new vegetable this week.",
 "Eat slowly; the day will wait.",
 "Drink water, eat fruit, sleep well, smile often.",
 "A balanced plate is half colour, half comfort.",
 "Start small: one more vegetable on today's plate.",
 "Your future self thanks you for tonight's salad.",
 "Good eating habits are built one meal at a time.",
 "Skip the rush; cook one simple dish today.",
 "Variety on the plate keeps boredom off the table.",
 "Pack fruits for the journey and smiles for the destination.",
 "Children learn to love vegetables by watching you enjoy them.",
 "Let kids wash the vegetables; they will eat what they helped with.",
 "Cooking together is a lesson no school can match.",
 "A packed lunch from home carries a little love along.",
 "Share a meal with a neighbour and the street feels like family.",
 "A dinner table is the world's smallest parliament; keep it peaceful.",
 "Put the phone away and taste the food.",
 "Mindful bites turn meals into moments.",
 "Thank the cook, always.",
 "Appreciation is the best garnish.",
 "Waste less, share more, and the table grows.",
 "Respect every grain; someone worked hard for it.",
 "Buy what you need, cook what you buy, enjoy what you cook.",
 "Plan the week, shop once, relax more.",
 "Store greens in a cool place and they will stay fresh longer.",
 "Keep leafy greens dry and they will last.",
 "Wrap coriander in a cloth and it stays fresh for days.",
 "Tomatoes ripen best on the counter, not in the cold.",
 "Wash vegetables just before cooking to keep them fresh.",
 "Keep onions and potatoes apart for longer shelf life.",
 "Ripe bananas are best for baking, green ones for frying.",
 "Lemon juice keeps cut fruit bright.",
 "A sharp knife is the cook's best friend.",
 "Taste as you go, and the dish will thank you.",
 "Season at the end, then taste again.",
 "Let the dish rest a few minutes and the flavours settle.",
 "The first rule of good cooking is good ingredients.",
 "Fresh herbs go in last, so their aroma stays.",
 "Heat the pan before the oil, and the oil before the spices.",
 "Cook rice with patience; it rewards you with softness.",
 "Soak your dal; it cooks faster and kinder.",
 "Steam vegetables lightly to keep their colour and crunch.",
 "A pinch of sugar rounds off a sharp tomato gravy.",
 "Fry onions slowly and the curry will be sweeter.",
 "Roast spices lightly to wake up their aroma.",
 "Fresh paste beats packet powder every time.",
 "A hot pan and a bit of courage make a crisp dosa.",
 "Let the pressure cooker whistle be your kitchen clock.",
 "Do not stir too much; let the vegetables be themselves.",
 "Measure with your eyes and correct with your tongue.",
 "Cooking improves with every attempt; keep going.",
 "A burnt dish is only a lesson with a smoky smell.",
 "No recipe is a failure if it was made with love.",
 "Cook for yourself as if you were a guest.",
 "It is never too late to learn a recipe.",
 "Every great cook was once a beginner with a burnt pan.",
 "Keep a little spice jar of courage ready.",
 "Food is the one gift everyone is happy to receive.",
 "Bring a dish, bring a smile.",
 "Share the extra; abundance grows when given.",
 "The best meals are not counted in calories but in memories.",
 "A hungry person remembers a kind meal forever.",
 "Feeding someone is the oldest way to say you matter.",
 "Never underestimate a simple plate of rice and kindness.",
 "A table laid with care invites good conversation.",
 "The warmth of a kitchen can outlast the coldest day.",
 "Lunch with family is the best break of the day.",
 "Light a lamp, serve the meal, give thanks.",
 "Dinner is the day's last chance to be together.",
 "A relaxed meal is the best digestion.",
 "Hurry is the enemy of enjoyment; sit, chew, savour.",
 "Hydration is the simplest self-care.",
 "Warm water in the morning, fresh fruit by noon, light dinner at night.",
 "Sleep early; vegetables are fresh in the morning.",
 "Go to the market early and meet the day at its best.",
 "Fresh air, fresh vegetables, fresh thoughts.",
 "Walk to the market when you can; the best things are found slowly.",
 "A good day is one that includes good food.",
 "A farmer rises before the sun so you can eat after it.",
 "Every harvest is a promise kept by the earth.",
 "Rain, soil, sun and a farmer's patience: that is the recipe.",
 "Behind every fresh vegetable is a long, quiet effort.",
 "Support the farmer and the farm will support you.",
 "The seed does not rush, and neither should we.",
 "A field in bloom is the best advertisement for fresh food.",
 "Fresh food travels short distances and carries long stories.",
 "Good soil is the first ingredient in every dish.",
 "Harvest time is thank-you time.",
 "Nature gives in seasons; wisdom is receiving each gladly.",
 "The land feeds a million without asking for a name.",
 "Honest farming leads to honest flavour.",
 "When we respect the soil, the soil respects the plate.",
 "Every green leaf is a small solar panel and a full meal.",
 "A field of lentils is a field of patience.",
 "Water the roots, and the fruit will follow.",
 "The mango tree remembers every summer and gives back.",
 "Coconut palms stand tall because they give much.",
 "Plant a tree today and eat from it tomorrow.",
 "Where the earth is cared for, the market is rich.",
 "Nothing teaches generosity like a fruiting tree.",
 "The humble potato fed the world through hard times.",
 "Every season has a vegetable that deserves to be your favourite.",
 "Fresh vegetables are patience delivered in a basket.",
 "A good harvest is a shared celebration.",
 "Respect the grain, and it will never leave your table.",
 "Small farms grow big flavours.",
 "Bountiful baskets begin with caring hands.",
 "Trust the market vendor who knows his tomatoes by name.",
 "A vegetable vendor's smile is the first ingredient of a good meal.",
 "The sweetest fruit comes from the most patient tree.",
 "A pinch of rain and a spoon of sun: the farmer's secret recipe.",
 "Wholesome food needs no disguise.",
 "The oldest superfood is a fresh vegetable.",
 "Eat what grows nearby and stay close to the seasons.",
 "Greens in the morning, grains at noon, light dinner at dusk.",
 "Honour hunger; it is the best cook.",
 "Rice, dal, a vegetable and a smile: the meal of every happy home.",
 "Plain curd rice, with a pickle on the side, never disappoints.",
 "Warm roti with ghee is a small act of kindness.",
 "Hot soup on a cold day is a lesson in simple comfort.",
 "A cool salad on a hot day is nature's air conditioner.",
 "Fresh juice is a sip of the season.",
 "A smoothie is a fruit basket in a glass.",
 "A snack of cut fruit is the easiest healthy habit.",
 "Fresh salads need only salt, lemon and attention.",
 "Roasted vegetables turn quiet kitchens into fragrant ones.",
 "Stir-fries are the quickest way to a colourful dinner.",
 "Soup is the gentlest way to eat your greens.",
 "Cutlets are just vegetables dressed for a party.",
 "Pickles are patience preserved.",
 "Chutneys are the small joys that complete a meal.",
 "A good thoran is just fresh vegetables and coconut in conversation.",
 "Poriyal is the humble poem of a South Indian meal.",
 "Kootu is comfort, cooked slowly.",
 "Sambar is the sunshine of the Tamil kitchen.",
 "Rasam is the answer to a cold, a cloud or a grey mood.",
 "Payasam is the full stop that makes every feast complete.",
 "A dash of coconut milk makes a stew feel like a holiday.",
 "Biryani is love layered with patience.",
 "Curd, mint and cucumber: a simple cool raita for a hot day.",
 "Fried brinjal is a pleasure that needs no explanation.",
 "Mashed potatoes: proof that comfort is simple.",
 "Jeera rice, dal fry and a night in: a perfect plan.",
 "Idli, dosa, pongal, vada: breakfast is a festival here.",
 "A plate of upma tastes better when someone made it for you.",
 "Sundal in the evening: a small walk in flavour.",
 "A paper cone of roasted peanuts on the beach: pure joy.",
 "Baked, boiled or fried, a potato is always welcome.",
 "Leftovers are just tomorrow's lunch in disguise.",
 "A well-timed snack is a small act of self-care.",
 "Never judge a cook by the length of the recipe.",
 "A table with a vegetable on it is never empty.",
 "Good food is a quiet celebration of being alive.",
 "Today's meal is a chance to feel nourished and thankful.",
 "Meals are meant to be shared, not hurried.",
 "A small kitchen can make a huge feast.",
 "You do not need a lot to cook well; you need freshness.",
 "Spice up the day with something new.",
 "Make today delicious.",
 "Take a breath, take a bite, take your time.",
 "Good food, good mood.",
 "Be generous at the table.",
 "Let your plate be the brightest thing today.",
 "What you eat today is what you will have energy for tomorrow.",
 "Eat to feel good, not to feel full.",
 "Be curious about vegetables you have never tried.",
 "Order fresh, cook fresh, feel fresh.",
 "The simplest ingredients make the most honest meals.",
 "Each tomato carries a little summer.",
 "Onions teach us that layers make us who we are.",
 "A potato in the pot is a promise of dinner.",
 "Carrots grow in the dark and still glow orange.",
 "Spinach never complains and always delivers.",
 "A cabbage is a green garden folded neatly.",
 "Beetroot paints the plate and warms the heart.",
 "Cauliflower is a quiet cloud on the plate.",
 "Brinjal wears purple like royalty.",
 "Capsicum shines in three colours and speaks in none.",
 "Cucumber: cool as the first monsoon drop.",
 "Radish brings a peppery spark to any plate.",
 "Drumstick is a stick of goodness.",
 "Green chillies are small but make big decisions.",
 "Peas are tiny green pearls in a pod.",
 "French beans are slim, crisp and cheerful.",
 "Broccoli is a tiny tree for your plate.",
 "Lady's finger: the small green finger of a good meal.",
 "Ridge gourd is the gentlest vegetable in the basket.",
 "Ash gourd is cool, calm and collected.",
 "Banana stem is the quiet worker of the kitchen.",
 "Yam is a rooted comfort.",
 "Colocasia, once cooked well, is a rare pleasure.",
 "Sweet corn is a row of little suns.",
 "A coriander bunch is a green bouquet for the kitchen.",
 "Mint leaves are nature's own refresh button.",
 "Fresh dill smells like a garden in a hurry.",
 "Spring onions are the green accent of the vegetable world.",
 "Garlic is small but never ignored.",
 "Ginger, the old friend of ailing days.",
 "Lemon gives and gives without asking anything.",
 "Raw mango makes the tongue and the heart tingle.",
 "Pomegranate seeds are edible jewels.",
 "Oranges are sunshine in segments.",
 "Apples: crisp days in a bite.",
 "Bananas come with their own wrapper and a smile.",
 "Grapes come in bunches, just like good news.",
 "Papaya is a sunrise on a plate.",
 "Guava is a modest fruit with a mighty scent.",
 "Watermelon: a picnic in every slice.",
 "Muskmelon is summer's sweet whisper.",
 "Pineapple is a crown that knows its worth.",
 "Sapota is honey in a brown coat.",
 "Custard apple is a treasure box of sweet segments.",
 "Jamun turns lips purple and moods bright.",
 "Fig is old-world sweetness.",
 "Pears are gentle fruits for gentle days.",
 "Kiwi: tiny, tangy, totally worth it.",
 "Berries are the small jewels of the fruit basket.",
 "Coconut is the fruit that gives food, drink and shade.",
 "Dates are nature's sweet little energy bars.",
 "Almonds are quiet strength in a shell.",
 "Cashews are crescent moons of crunch.",
 "Raisins are small grapes with big memories.",
 "Peanuts are the poor man's pearls.",
 "Sesame is tiny but never lost in a recipe.",
 "Jaggery, ghee and rice flour: a festival in three words.",
 "Tamarind is the tangy memory of a childhood kitchen.",
 "Curry leaves are the quiet signature on every dish.",
 "Coriander seeds crackle with warmth.",
 "Fennel gives a gentle sweetness at the end of a meal.",
 "Cumin is the earthy heartbeat of Indian cooking.",
 "Cinnamon whispers of faraway hills.",
 "Pepper is bold, black and beautiful.",
 "Cardamom is the queen of spices.",
 "Bay leaf is the unsung hero of the pot.",
 "Saffron is sunshine concentrated.",
 "Mustard seeds start every good conversation in the pan.",
 "Chilli flakes bring adventure to a meal.",
 "Coconut oil is the scent of home.",
 "Ghee is liquid gold on warm rice.",
 "Butter melts, and so do worries.",
 "Milk begins the morning and ends the night gently.",
 "Curd is the cool, quiet strength of every meal.",
 "Buttermilk: spiced with ginger and happiness.",
 "Eggs are the breakfast that never lets you down.",
 "Rice is the grain that holds the world together.",
 "Wheat is the daily bread of billions.",
 "Ragi is old grain, new strength.",
 "Oats are patience in a bowl.",
 "Dal is a pot of quiet wealth.",
 "Chickpeas are tiny energy pellets.",
 "Rajma is a hug in red.",
 "Moong sprouts are green hope.",
 "Tofu takes the flavour of whatever kindness you give it.",
 "Today's fresh is tomorrow's memory.",
 "A plate of fresh food is a small gift to your future self.",
 "Every purchase from a farmer's hand feeds a family twice.",
 "A smile is the best side dish.",
 "Let the kitchen be your happy place.",
 "Good ingredients forgive small mistakes.",
 "A little extra vegetable never hurt anybody.",
 "Take care of your kitchen and it will take care of you.",
 "Food tastes best when it is not rushed.",
 "Treat every meal as a small celebration.",
 "Happy bellies, happy homes.",
 "The first spoon of any meal should be gratitude.",
 "Be someone's reason to enjoy dinner.",
 "Fresh vegetables: the cheapest way to feel rich.",
 "A meal at home is a coin of comfort saved.",
 "Good things come to those who cook.",
 "Do small things with great flavour.",
 "Make room for fruit in every day.",
 "If it grows, it is probably good for you.",
 "Fresh food never goes out of style.",
 "Be fresh, be kind, be well.",
 "Treat vegetables like friends and they will treat you well.",
 "The pot does not boil faster for watching; breathe.",
 "Dinner can wait; gratitude cannot.",
 "Meals made of fresh vegetables never need an excuse.",
 "Let your meals be as colourful as your dreams.",
 "Strong roots make sweet fruit.",
 "Live simply, eat freshly.",
 "Enjoy life's small pleasures, especially the edible ones.",
 "A plate of freshness is a smile in advance.",
 "Today, choose the greener plate.",
 "To be nourished is to be cared for.",
 "Anything cooked with kindness tastes better.",
 "A sweet fruit is a fine way to end a hard day.",
 "Better a fresh bite than a long wish.",
 "When the ingredients are fresh, the cook is brave.",
 "The best dinner guests are the ones who help wash the greens.",
 "Nothing nourishes like food shared with those we love.",
 "We eat with our eyes first, so keep the plate pretty.",
 "A neat kitchen is a happy beginning.",
 "Sometimes a bowl of curd rice is all the therapy you need.",
 "There is no sauce like hunger and no spice like friendship.",
 "A glass of cold water and a bowl of fruit: simple wealth.",
 "Lighten the plate, lighten the mood.",
 "Dream big, cook simple.",
 "Go gently; the best flavours need time.",
 "Keep your pantry kind and your fridge friendly.",
 "A fresh start can begin with a fresh breakfast.",
 "Let each bite remind you of the farmer who grew it.",
 "Where food is fresh, hearts are open.",
 "The first rule of the kitchen: wash your hands and smile.",
 "Leaves, roots, flowers, fruits: nature feeds us in every shape.",
 "Appetite is the best compliment to the cook.",
 "Wake up your day with a fruit.",
 "A little coriander sprinkled is a little joy served.",
 "Bring the market home and the home blooms.",
 "We are what we eat, so eat what you would love to become.",
 "A meal is a mood; choose a good one.",
 "Fresh produce is a daily invitation to feel well.",
 "Food brings people to the same table and the same laughter.",
 "The recipe for a good day: fresh start, light lunch, kind dinner.",
 "You cannot rush a good rasam.",
 "The kitchen is the kindest classroom.",
 "A bright vegetable is a bright start.",
 "Great taste is just fresh ingredients meeting patience.",
 "Shop fresh, cook kind, live well.",
 "In every cut mango, there is a summer afternoon.",
 "Wash, chop, cook, smile.",
 "The best kind of busy is a kitchen full of aroma.",
 "Let your hands be warm and your vegetables fresher.",
 "Treat yourself to something green today.",
 "Fresh ingredients bring out the best in every cook.",
 "Spoon by spoon, a good day builds.",
 "The beauty of food is that it brings everyone home.",
 "Nourish your body, nurture your mind.",
 "Make a little time for a lot of taste.",
 "With fresh vegetables in hand, any kitchen is a studio.",
 "Cook with what you have, add what is fresh.",
 "Every thali tells the story of a good day.",
 "Look for colour, smell for freshness, feel for firmness.",
 "Pick vegetables the way you pick friends: for freshness and character.",
 "Fruit is the sweetest way to be healthy.",
 "Every spoon of home food is a spoon of comfort.",
 "There is always a good reason to eat something fresh.",
 "The best breakfast is the one eaten slowly.",
 "You can taste the difference when food is made with love.",
 "Happiness is a hot meal and nowhere to rush.",
 "Sweet words and sweet mangoes make the best summer.",
 "Good company is the best seasoning at any table.",
 "Let every plate you serve be an act of kindness.",
 "A fresh start is a basket away.",
 "A kitchen without a vegetable is a stage without a hero.",
 "Our grandmothers cooked without timers and never overcooked.",
 "Rice taught the world how to share.",
 "A feast is only a meal with more friends.",
 "Be as fresh as the morning greens.",
 "Leaf by leaf, we build good health.",
 "Small bites, big gratitude.",
 "Enjoy the ordinary meal; it is the most common miracle.",
 "Let food be simple, safe and shared.",
 "Nothing is as comforting as the smell of something cooking at home.",
 "Fresh veggies are the language of love in a busy world.",
 "A basket of vegetables is a basket of choices; choose well.",
 "The kitchen window always faces happiness.",
 "May your pots always be full and your spirits fuller.",
 "Good food invites good talk.",
 "Look after the little things on the plate.",
 "A balanced meal begins with a balanced mind.",
 "An honest meal is always the best meal.",
 "Great days start with a good market run.",
 "Keep it local, keep it seasonal, keep it simple.",
 "There is no better time to eat fresh than now.",
 "What is fresh today cannot wait for tomorrow.",
 "Good taste is only fresh produce and a quiet kitchen.",
 "Cook what makes you feel at home.",
 "Taste is memory; fresh is memory's best friend.",
 "Be proud of your plate.",
 "Vegetables like attention: wash, chop, cook, enjoy.",
 "Gather your vegetables and gather your thoughts.",
 "Every kitchen has a heartbeat; it is the sizzle.",
 "Cooking is the art of turning ingredients into belonging.",
 "Fresh produce is the best piece of art in any market.",
 "A cup of rasam is worth a hundred words of comfort.",
 "Be generous with the curry leaves and the compliments.",
 "A little salt, a little sweetness, a lot of heart.",
 "Pick what is ripe, leave what is not, wait for what will be.",
 "Whatever you cook, cook it with full attention.",
 "Fruits do not argue; they simply ripen.",
 "Fresh produce is the nicest thing you can bring home.",
 "A home with fresh vegetables is a home with a plan.",
 "Be the friend who brings fruit.",
 "Good food is a soft way to say good morning.",
 "Appreciate the little things: a clean kitchen, a hot pan, a fresh herb.",
 "A meal of fresh vegetables is a gift you open every day.",
 "Vegetables are happiest when they are used the same day.",
 "Eat early, laugh often, rest well.",
 "It is the small portions of care that make a big meal.",
 "Eat what is fresh, cook what is simple, share what is extra.",
 "Wholesome meals build wholesome days.",
 "The brighter the vegetable, the brighter the day.",
 "Every mealtime is another small thank-you.",
 "Eat in good company and every dish will taste better.",
 "Good food is not loud; it just fills the room with smiles.",
 "Today's special is gratitude.",
 "Treasure the people who cook for you.",
 "Celebrate the freshness of ordinary things.",
 "A hot meal on a cold evening is the simplest luxury.",
 "Fresh herbs, warm bread, kind words.",
 "Aroma is the first taste.",
 "You never regret a fresh meal.",
 "Be as colourful as your fruit bowl.",
 "Savour what is here before reaching for what is next.",
 "A little humour in the kitchen keeps the rice from burning.",
 "The best chefs wash their hands and their worries first.",
 "Appreciate the colour green; it feeds us in many ways.",
 "Every day is a good day for a good vegetable.",
 "Balance your day the way you balance your plate.",
 "Fresh produce, fresh prices, fresh smiles.",
 "Flavour comes from freshness, not from fuss.",
 "The lowest-effort kind of luxury is a fresh fruit.",
 "You are what you eat; so eat something wonderful.",
 "The right vegetable at the right time is a quiet triumph.",
 "A good meal is half preparation and half appreciation.",
 "When in doubt, go to the market.",
 "Nothing beats the morning smell of fresh greens.",
 "Eat slowly, your kitchen worked hard.",
 "Tomatoes ripen the same way kindness grows: slowly and then all at once.",
 "Be the onion of the family: always in the middle of good things.",
 "The wise cook buys fresh, cooks lightly, serves warm.",
 "Eat fruit, speak sweet.",
 "Be like a ripe fruit: sweet inside and ready to share.",
 "Seasonal food is the earth's way of saying, try this now.",
 "The best food memory is usually the simplest.",
 "Slow cooking is the opposite of rushing through life.",
 "Let the vegetables steam while you take a deep breath.",
 "Make your kitchen a place of peace and your plate a place of colour.",
 "A bowl of dal is poetry for the poor and the rich alike.",
 "You can feel love in a handmade chapati.",
 "If you want to understand a culture, eat its home food.",
 "Take food seriously and life lightly.",
 "A handful of fresh herbs will rescue any dish.",
 "Cooking is not about perfection; it is about presence.",
 "Taste the world, one fresh plate at a time.",
 "You will never hear anyone regret a home-cooked meal.",
 "When you cook with fresh vegetables, the kitchen sings.",
 "Bake the bread, boil the dal, bless the day.",
 "A home-cooked meal is a hug with a spoon.",
 "Every bite is a vote for the kind of life you want.",
 "Be thankful for hot food and a safe table.",
 "A well-stocked vegetable basket is a well-stocked week.",
 "Cook as if the whole family will taste your care.",
 "The best table decorations are fresh vegetables.",
 "You can grow a lot of joy in a small kitchen.",
 "When life gives you tomatoes, make rasam.",
 "When life gets sour, add a little jaggery.",
 "A good cook is a good listener.",
 "Add a little humour and a lot of vegetables.",
 "You cannot cook happiness, but you can cook the next best thing.",
 "Be patient: the best curries take time.",
 "The scent of freshly ground masala is the scent of a good day.",
 "Fresh produce does not need a filter.",
 "Good food is a good friend.",
 "Little acts of kindness can be served with rice.",
 "Hot, fresh and homemade: three words for a happy house.",
 "Eat the leaf and bless the tree.",
 "Choose food that makes your body smile.",
 "Take the day one meal at a time.",
 "Eat a little, share a little, smile a lot.",
 "Nourishment is more than food; it is food with care.",
 "Fruit is the sweetest reminder that nature wants us well.",
 "A slow Sunday lunch is a gift to the week ahead.",
 "Sundays are for sambar and second helpings.",
 "A well-chosen vegetable can change an entire week.",
 "Keep your day simple and your dinner fresh.",
 "Great flavour starts at the market, not in the pan.",
 "Cook for the pleasure of it.",
 "Good food is a fine reason to slow down.",
 "The best seat in the house is next to the kitchen.",
 "Never trust a day that has no meal worth remembering.",
 "Good food, kind words, long evenings.",
 "Kindness grows best in a well-fed home.",
 "Everything feels better after a warm meal.",
 "Feed the people you love, and feed them well.",
 "A hearty meal today is a reason to smile tomorrow.",
 "Let freshness guide your basket and gratitude guide your plate.",
 "The finest dinner is cooked with fresh produce and a clear mind.",
 "One good vegetable can change the whole thali.",
 "You deserve a fresh plate today.",
 "Treat every ingredient with respect and it will return the favour.",
 "Cooking is a conversation between your hands and the earth.",
 "Fresh market, fresh kitchen, fresh mind.",
 "A pot on the stove is a heart at home.",
 "Fresh basil, warm tomatoes: summer on a plate.",
 "Dinner tastes better when the day has been kind.",
 "Good food never asks for applause, just a second helping.",
 "Give your family the gift of a fresh meal today.",
 "Treasure the aroma of tempering; it means someone cares.",
 "The cook who tastes before serving serves twice as well.",
 "A fruit plate is a smile you can eat.",
 "Be generous with fruits, and the day will be generous with you.",
 "A meal with a vegetable in it is a meal with a future.",
 "Even a small potato is a big comfort.",
 "Choose freshness, and let the dish do the rest.",
 "Our body is a garden; feed it flowers, fruit and leaves.",
 "The shorter the journey from farm to plate, the better the flavour.",
 "A busy day deserves a simple, fresh dinner.",
 "Remember to thank the hands that hold the harvest.",
 "The sound of a pressure cooker is the sound of home.",
 "The market is where you meet the season.",
 "A ripe tomato does not need decoration.",
 "Make time for slow mornings and fresh fruit.",
 "Pause, sip, savour; life's best moments are small.",
 "Not every treasure is gold; some are green and leafy.",
 "May your plate be bright and your heart be light.",
 "Harvest each day the way a farmer harvests his field: with thanks.",
 "Whether you cook for one or ten, cook with love.",
 "The meal is complete when someone says thank you.",
 "Fresh produce is the language of care.",
 "A spoon of fresh chutney is a smile on a plate.",
 "Live in colour and eat in colour.",
 "Fresh groceries make for a fresh week.",
 "A basket of fresh vegetables never disappoints.",
 "Moderation makes everything taste better.",
 "Add a dash of patience to everything you cook.",
 "Happiness is homemade.",
 "The best meals are measured in smiles, not in portions.",
 "Vegetables are best friends with every spice.",
 "If your plate is colourful, your day will be too.",
 "Savour the freshness, you earned it.",
 "A well-planned basket makes a well-run kitchen.",
 "Make a habit of fresh food and the habit will make you.",
 "Wholesome and fresh is the simplest recipe for happiness.",
 "Share the harvest, share the joy.",
 "An honest tomato is a sweet one.",
 "Be proud of what your kitchen creates.",
 "A simple meal can hold a great deal of love.",
 "Food is love you can hold in your hands.",
 "Fresh vegetables change the mood of the whole house.",
 "Aromas travel faster than words; let your kitchen speak.",
 "Real flavour needs real ingredients.",
 "The path to a good mood is paved with good produce.",
 "A fresh meal is a fresh chance to care.",
 "Slow down and the soup will taste better.",
 "An ordinary day becomes special with one thoughtful meal.",
 "Bring in the greens and the house turns brighter.",
 "Each fresh meal is a small thank-you to yourself.",
 "The best gift: a dinner cooked with fresh produce.",
 "Start the day with a bright fruit and a bright thought.",
 "You do not need much to be nourished; you need fresh.",
 "Good vegetables do half the cooking for you.",
 "A kind kitchen feeds more than the stomach.",
 "When the basket is full, the heart is too.",
 "There is no wrong time for a fresh fruit.",
 "Good meals take care of you when no one else can.",
 "Give thanks for what is on the plate and who is at the table.",
 "Fresh air outside, fresh produce inside.",
 "Have a heart as fresh as your vegetables.",
 "Smile at the vendor, smile at the vegetables, smile at the day.",
 "Thank your food before you eat it.",
 "The best part of any recipe is the sharing.",
 "Good things come in baskets.",
 "Fresh greens bring fresh energy.",
 "A farmer's work is the beginning of every happy meal.",
 "Fresh to the market, fresh to your door.",
 "A well-made meal is its own reward.",
 "Appreciate the effort behind every ingredient.",
 "Fresh vegetables keep the day lively.",
 "Savour each season in its own fruit.",
 "A grateful heart makes every meal a feast.",
 "Let food bring you together.",
 "Good morning is better with fresh fruit.",
 "Good afternoon is better with a long lunch.",
 "Good evening is better with warm snacks.",
 "Good night is better with a light dinner.",
 "Let your morning start with water and fruit.",
 "Noon is for a proper meal, shared and unhurried.",
 "Evenings smell of tea, tempering and tales.",
 "A gentle dinner makes for a gentle sleep.",
 "Weekends are for markets and slow cooking.",
 "Sundays smell of sambar and rest.",
 "Mondays need a good breakfast.",
 "Tuesdays deserve a new vegetable.",
 "Wednesdays go better with dal and rice.",
 "Thursdays were made for light, fresh dinners.",
 "Fridays call for a little treat and a lot of gratitude.",
 "Saturdays are for the market and for family lunch.",
 "New week, new vegetables.",
 "The first day of the month deserves something sweet.",
 "Festival days are for sharing the meal with everyone.",
 "Birthdays taste best when there is payasam.",
 "Rainy days call for hot bajjis and good conversation.",
 "Hot days call for cool curd and juicy fruit.",
 "Cold days call for warm soup and warm company.",
 "Spring brings tender greens and tender thoughts.",
 "Summer brings mangoes and long, lazy afternoons.",
 "Monsoon brings corn, ginger tea and cozy corners.",
 "Autumn brings pumpkins and a golden light.",
 "Winter brings oranges, peas and long dinners.",
 "Harvest season is thanksgiving in every home.",
 "New year, new fruit on the table.",
 "Welcome the day with something fresh and green.",
 "Welcome guests with something sweet and warm.",
 "Welcome yourself with something nourishing.",
 "A home that smells of cooking is a home that welcomes.",
 "A lunchbox from home is a letter from love.",
 "The tiffin carrier is the original lunch delivery of love.",
 "A mother's meal is the best meal anywhere.",
 "A father's tea is the best tea anywhere.",
 "Grandmother's pickle is the best pickle anywhere.",
 "A friend's kitchen is the best kitchen anywhere.",
 "A child's first bite of fruit is a lovely thing to witness.",
 "Cook for the people who matter, starting with yourself.",
 "Appreciate the dishes that never made it to a cookbook.",
 "Treasure recipes that were never written, only remembered.",
 "Teach someone to cook and you feed them for life.",
 "The best cookbook is a curious mind.",
 "Learn one new dish this month.",
 "Visit a market in a new town and meet its people through food.",
 "When travelling, eat what the locals eat.",
 "Home is where your favourite meal is waiting.",
 "Fresh produce is one of the nicest surprises in the day.",
 "Be kind to the person who cooked; be kinder to the person who grew.",
 "The smell of fresh bread is a smell of hope.",
 "Fresh juice is a refreshing break in a busy day.",
 "A day without fresh fruit is a day half-lived.",
 "A clean plate is the cook's favourite compliment.",
 "A grateful guest is the best gift to any host.",
 "Hospitality begins in the kitchen.",
 "A full table is a full heart.",
 "Every meal is a chance to teach kindness to a child.",
 "A meal is more than food; it is an event.",
 "A simple dinner with loved ones is better than a banquet alone.",
 "Good food does not need a reason; it needs a table.",
 "There is great beauty in a basket of fresh greens.",
 "Slow down your shopping and speed up your smiles.",
 "Pick vegetables with your hands, not just your eyes.",
 "The best produce is the one picked today.",
 "Let seasons decide your menu.",
 "Be grateful for the cooks who feed you every day.",
 "It's okay to have dessert first if it is a ripe mango.",
 "Fresh fruit never needs an occasion.",
 "A fresh vegetable is always in fashion.",
 "Healthy eating is a habit of kindness to yourself.",
 "Let your kitchen be the place you return to.",
 "Fresh produce, fresh promises.",
 "Appreciate the colours that nature plants on your plate.",
 "A basket today, a feast tomorrow.",
 "Eat a little fruit before the day begins.",
 "Cooking is gratitude with a flame.",
 "Fresh vegetables, fresh vows: eat well, live well.",
 "Savour the day like a ripe mango.",
 "Fresh is the first flavour.",
 "When the plate is happy, the person is happy.",
 "The best aroma in the world is dinner at home.",
 "The simplest dish can be the most special.",
 "Share a fruit, share a smile.",
 "Warm rice, soft dal, cool curd: a perfect little trio.",
 "Always make room for something green.",
 "Make your meals as bright as your mornings.",
 "Treat the vendor kindly; he knows your tomatoes better than you.",
 "Thankful hearts cook the tastiest meals.",
 "Bring home fresh and the whole week brightens.",
 "A thoughtful meal turns a Tuesday into a treat.",
 "There is joy in the chopping, the sizzle and the first taste.",
 "Fresh vegetables are the best make-up for a pale plate.",
 "Add a smile, it needs no recipe.",
 "Hands that cook with love leave a lasting taste.",
 "A kitchen full of fresh produce is a kitchen full of possibilities.",
 "Simple wholesome food is the happiest kind.",
 "Lunch is a pause button for the soul.",
 "Never skip the fruit; it is the day's little gift.",
 "Your lunchbox is a love letter to your body.",
 "Fresh food is a daily act of self-respect.",
 "Gratitude is the best appetiser.",
 "Good things take time; so do good curries.",
 "Good flavour is a form of kindness.",
 "Food is the world's first and favourite language.",
 "A seed, a farmer, a market, a kitchen: that is a miracle.",
 "Let every day have its own fresh flavour.",
 "Enjoy every bite as if it were the first.",
 "Let your meals be the calm in your busy day.",
 "Fresh ingredients: the quiet confidence of a good cook.",
 "A well-fed day is a well-lived day.",
 "Every pot has a story; make yours a good one.",
 "Savour the slow things: rice, rain and rasam.",
 "Pause for a fruit, it is a small holiday.",
 "Fresh meals make fresh memories.",
 "Chop mindfully, cook calmly, eat gratefully.",
 "There is poetry in a basket of vegetables.",
 "May every meal bring you comfort, colour and company.",
 "Appreciate the leaf, the root, the fruit, the seed.",
 "Fruits are happiest when shared.",
 "Good eating is a way of saying yes to life.",
 "A meal shared is a bond made.",
 "Warm food has a way of mending the day.",
 "Treat your kitchen like a garden and it will bloom.",
 "Be fresh in thought and in plate.",
 "A basket of greens is a basket of hope.",
 "Always welcome fresh ideas and fresh vegetables.",
 "Some days need only dal, rice and kindness.",
 "Love your vegetables and they will love you back.",
 "A tray of cut fruit is the friendliest snack.",
 "Taste the world, one fresh mouthful at a time.",
 "Small kitchens make big memories.",
 "Grow what you can, buy what you cannot, share what you have.",
 "When the market is fresh, the meal is already half cooked.",
 "Cook with the day's best produce and the day's best mood.",
 "Let your food be fresh enough to be remembered.",
 "Choose well, cook with heart, serve with a smile.",
 "The colour of good health is every colour on the plate.",
 "Every ripe fruit is a reminder to be patient.",
 "The finest ingredient is a calm heart.",
 "A well-fed family is a well-loved family.",
 "A good market day lasts all week.",
 "The scent of ripe fruit is a quiet joy.",
 "A basket full of colour is a basket full of life.",
 "Make every day a little more delicious.",
 "Every plate can hold a little poetry.",
 "Fresh vegetables are small acts of care.",
 "The best things in life are fresh and shared."
];

const DAY_MS = 24 * 60 * 60 * 1000;

/** Thought for a given date (defaults to today). Same date -> same thought. */
export function thoughtForDate(date = new Date()) {
  const d = date instanceof Date ? date : new Date(date);
  const dayNumber = Math.floor((Date.UTC(d.getFullYear(), d.getMonth(), d.getDate())) / DAY_MS);
  return FOOD_THOUGHTS[((dayNumber % FOOD_THOUGHTS.length) + FOOD_THOUGHTS.length) % FOOD_THOUGHTS.length];
}
